/*
 * Copyright (C) 2020 tonikelope
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */
package com.tonikelope.coronapoker;

import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import java.awt.image.BufferedImage;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Base64;
import java.util.Iterator;
import java.util.Locale;
import java.util.Set;
import javax.imageio.ImageIO;
import javax.imageio.ImageReader;
import javax.imageio.metadata.IIOMetadata;
import javax.imageio.stream.ImageInputStream;
import org.w3c.dom.NamedNodeMap;
import org.w3c.dom.Node;

/**
 * Validates untrusted wire avatars before any Swing/ImageIO rasterization and
 * owns the temporary files created for them.
 */
public final class AvatarIO {

    public static final int MAX_DECODED_BYTES = 256 * 1024;
    public static final int MAX_ENCODED_CHARS = 4 * ((MAX_DECODED_BYTES + 2) / 3);
    public static final int MAX_DIMENSION = 4096;
    public static final long MAX_FRAME_PIXELS = 4_194_304L;
    public static final int MAX_FRAMES = 32;
    public static final long MAX_TOTAL_FRAME_PIXELS = 8_388_608L;

    private static final Set<String> ALLOWED_FORMATS = Set.of("PNG", "JPEG", "GIF");
    private final Path sessionDirectory;
    private boolean closed;

    /**
     * Creates an isolated store below the JVM temporary directory.
     */
    public static AvatarIO createDefault() {
        try {
            return new AvatarIO(Path.of(System.getProperty("java.io.tmpdir")));
        } catch (IOException | RuntimeException ex) {
            return new AvatarIO();
        }
    }

    /**
     * Test seam and explicit-root constructor.
     */
    public AvatarIO(Path parentDirectory) throws IOException {
        Files.createDirectories(parentDirectory);
        sessionDirectory = Files.createTempDirectory(parentDirectory, "coronapoker-avatar-session-")
                .toAbsolutePath().normalize();
    }

    private AvatarIO() {
        sessionDirectory = null;
    }

    public Path getSessionDirectory() {
        return sessionDirectory;
    }

    /**
     * Decodes, validates and stores an untrusted Base64 avatar. The file is not
     * created until every size and metadata check has passed.
     */
    public synchronized File decodeValidateStore(String encoded) throws IOException {
        if (encoded == null || encoded.isEmpty() || "*".equals(encoded)) {
            return null;
        }
        if (sessionDirectory == null || closed) {
            throw new IOException("Avatar temporary store is unavailable");
        }
        if (encoded.length() > MAX_ENCODED_CHARS) {
            throw new IOException("Encoded avatar exceeds size limit");
        }

        final byte[] bytes;
        try {
            bytes = Base64.getDecoder().decode(encoded);
        } catch (IllegalArgumentException ex) {
            throw new IOException("Avatar is not strict Base64", ex);
        }
        if (bytes.length == 0 || bytes.length > MAX_DECODED_BYTES) {
            throw new IOException("Decoded avatar exceeds size limit");
        }

        validateImageMetadata(bytes);

        Path target = Files.createTempFile(sessionDirectory, "avatar-", ".img");
        boolean complete = false;
        try {
            Files.write(target, bytes);
            complete = true;
            return target.toFile();
        } finally {
            if (!complete) {
                Files.deleteIfExists(target);
            }
        }
    }

    /**
     * Deletes a file only when this store created/owns its parent directory.
     */
    public synchronized boolean deleteOwned(File file) {
        if (file == null || sessionDirectory == null) {
            return false;
        }
        Path candidate = file.toPath().toAbsolutePath().normalize();
        if (!sessionDirectory.equals(candidate.getParent())) {
            return false;
        }
        try {
            return Files.deleteIfExists(candidate);
        } catch (IOException ex) {
            return false;
        }
    }

    public synchronized boolean owns(File file) {
        if (file == null || sessionDirectory == null) {
            return false;
        }
        Path candidate = file.toPath().toAbsolutePath().normalize();
        return sessionDirectory.equals(candidate.getParent());
    }

    /**
     * Removes both the full avatar and the thumbnail generated by Participant.
     */
    public synchronized void deleteAvatarArtifacts(File avatar) {
        if (!owns(avatar)) {
            return;
        }
        deleteOwned(new File(avatar.getAbsolutePath() + "_chat"));
        deleteOwned(avatar);
    }

    /**
     * Writes the bounded in-chat thumbnail under the same ownership/close lock.
     */
    public synchronized File writeThumbnail(File avatar, BufferedImage thumbnail) throws IOException {
        if (closed || !owns(avatar) || thumbnail == null) {
            throw new IOException("Avatar store is closed or does not own the avatar");
        }
        File target = new File(avatar.getAbsolutePath() + "_chat");
        boolean complete = false;
        try {
            if (!ImageIO.write(thumbnail, "png", target)) {
                throw new IOException("No PNG writer available for avatar thumbnail");
            }
            complete = true;
            return target;
        } finally {
            if (!complete) {
                Files.deleteIfExists(target.toPath());
            }
        }
    }

    /**
     * Final logical-session cleanup; never follows or targets paths outside
     * this store.
     */
    public synchronized void close() {
        closed = true;
        if (sessionDirectory == null
                || !sessionDirectory.getFileName().toString().startsWith("coronapoker-avatar-session-")) {
            return;
        }
        try (java.util.stream.Stream<Path> paths = Files.walk(sessionDirectory)) {
            paths.sorted(java.util.Comparator.reverseOrder()).forEach(path -> {
                try {
                    Files.deleteIfExists(path);
                } catch (IOException ignored) {
                }
            });
        } catch (IOException ignored) {
        }
    }

    private static void validateImageMetadata(byte[] bytes) throws IOException {
        try (ImageInputStream input = ImageIO.createImageInputStream(new ByteArrayInputStream(bytes))) {
            if (input == null) {
                throw new IOException("Unable to inspect avatar image");
            }
            Iterator<ImageReader> readers = ImageIO.getImageReaders(input);
            if (!readers.hasNext()) {
                throw new IOException("Unsupported avatar image");
            }

            ImageReader reader = readers.next();
            try {
                String format = reader.getFormatName().toUpperCase(Locale.ROOT);
                if (!ALLOWED_FORMATS.contains(format)) {
                    throw new IOException("Unsupported avatar format: " + format);
                }
                reader.setInput(input, false, true);
                int frames = reader.getNumImages(true);
                if (frames < 1 || frames > MAX_FRAMES) {
                    throw new IOException("Avatar frame count exceeds limit");
                }

                int[] gifCanvas = "GIF".equals(format) ? validateGifCanvas(reader.getStreamMetadata()) : null;
                long gifCanvasPixels = gifCanvas == null
                        ? 0L : Math.multiplyExact((long) gifCanvas[0], (long) gifCanvas[1]);

                long totalPixels = 0L;
                for (int index = 0; index < frames; index++) {
                    int width = reader.getWidth(index);
                    int height = reader.getHeight(index);
                    validateExtent(width, height, "frame");
                    // Animated GIF decoders compose each subframe onto a logical canvas.
                    // Charge that retained canvas for every frame, not merely the usually
                    // tiny changed rectangle advertised by the subframe.
                    long retainedPixels = gifCanvas == null
                            ? Math.multiplyExact((long) width, (long) height) : gifCanvasPixels;
                    totalPixels = Math.addExact(totalPixels, retainedPixels);
                    if (totalPixels > MAX_TOTAL_FRAME_PIXELS) {
                        throw new IOException("Avatar total pixels exceed limit");
                    }
                    if (gifCanvas != null) {
                        validateGifFrame(reader.getImageMetadata(index), width, height,
                                gifCanvas[0], gifCanvas[1]);
                    }
                }
            } catch (ArithmeticException ex) {
                throw new IOException("Avatar dimensions overflow", ex);
            } finally {
                reader.dispose();
            }
        }
    }

    private static void validateExtent(int width, int height, String label) throws IOException {
        if (width <= 0 || height <= 0 || width > MAX_DIMENSION || height > MAX_DIMENSION
                || (long) width * (long) height > MAX_FRAME_PIXELS) {
            throw new IOException("Avatar " + label + " dimensions exceed limit");
        }
    }

    private static int[] validateGifCanvas(IIOMetadata metadata) throws IOException {
        Node descriptor = findNode(metadata, "javax_imageio_gif_stream_1.0", "LogicalScreenDescriptor");
        if (descriptor == null) {
            throw new IOException("GIF logical canvas metadata is missing");
        }
        int width = intAttribute(descriptor, "logicalScreenWidth");
        int height = intAttribute(descriptor, "logicalScreenHeight");
        validateExtent(width, height, "GIF canvas");
        return new int[]{width, height};
    }

    private static void validateGifFrame(IIOMetadata metadata, int width, int height,
            int canvasWidth, int canvasHeight) throws IOException {
        Node descriptor = findNode(metadata, "javax_imageio_gif_image_1.0", "ImageDescriptor");
        if (descriptor == null) {
            throw new IOException("GIF frame metadata is missing");
        }
        long left = intAttribute(descriptor, "imageLeftPosition");
        long top = intAttribute(descriptor, "imageTopPosition");
        if (left < 0 || top < 0 || left + width > canvasWidth || top + height > canvasHeight) {
            throw new IOException("GIF frame lies outside bounded canvas");
        }
    }

    private static Node findNode(IIOMetadata metadata, String format, String name) throws IOException {
        if (metadata == null) {
            return null;
        }
        Node root;
        try {
            root = metadata.getAsTree(format);
        } catch (IllegalArgumentException ex) {
            throw new IOException("Malformed avatar metadata", ex);
        }
        return findNode(root, name);
    }

    private static Node findNode(Node node, String name) {
        if (node == null) {
            return null;
        }
        if (name.equals(node.getNodeName())) {
            return node;
        }
        for (Node child = node.getFirstChild(); child != null; child = child.getNextSibling()) {
            Node found = findNode(child, name);
            if (found != null) {
                return found;
            }
        }
        return null;
    }

    private static int intAttribute(Node node, String name) throws IOException {
        NamedNodeMap attributes = node.getAttributes();
        Node attribute = attributes == null ? null : attributes.getNamedItem(name);
        if (attribute == null) {
            throw new IOException("Missing avatar metadata attribute " + name);
        }
        try {
            return Integer.parseInt(attribute.getNodeValue());
        } catch (NumberFormatException ex) {
            throw new IOException("Invalid avatar metadata attribute " + name, ex);
        }
    }
}
