/*
 * Copyright (C) 2020 tonikelope
 _              _ _        _                  
| |_ ___  _ __ (_) | _____| | ___  _ __   ___ 
| __/ _ \| '_ \| | |/ / _ \ |/ _ \| '_ \ / _ \
| || (_) | | | | |   <  __/ | (_) | |_) |  __/
 \__\___/|_| |_|_|_|\_\___|_|\___/| .__/ \___|
 ____    ___  ____    ___  
|___ \  / _ \|___ \  / _ \ 
  __) || | | | __) || | | |
 / __/ | |_| |/ __/ | |_| |
|_____| \___/|_____| \___/ 

https://github.com/tonikelope/coronapoker
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.tonikelope.coronapoker;

import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 * Panel wrapping a {@link GifLabel}, optionally painting the table's brightness
 * overlay on top of it.
 *
 * @author tonikelope
 */
public class GifPanel extends javax.swing.JPanel {

    private boolean brillo = true;

    // paint() is intentional here (not paintComponent): the overlay must be
    // drawn after paintChildren so it sits on top of the GifLabel.
    @Override
    public void paint(Graphics g) {
        super.paint(g);

        if (brillo && GameFrame.getInstance() != null) {
            GameFrame.getInstance().getCapa_brillo().paintOverlay(g, getWidth(), getHeight());
        }
    }

    /**
     * Creates a panel with the brightness overlay enabled.
     */
    public GifPanel() {
        initComponents();

    }

    /**
     * @param b whether to paint the brightness overlay on top of the gif
     */
    public GifPanel(boolean b) {
        initComponents();
        brillo = b;
    }

    public void setGifIcon(ImageIcon icon, int w, int h) {
        // Pass the icon unscaled: getScaledInstance is CPU-heavy, so scaling
        // is left to the label/hardware instead.
        gif.setIcon(icon);

        gif.setPreferredSize(new Dimension(w, h));
        setPreferredSize(new Dimension(w, h));
    }

    public GifLabel getGif() {
        return gif;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gif = new com.tonikelope.coronapoker.GifLabel();

        setFocusable(false);

        gif.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gif, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gif, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.tonikelope.coronapoker.GifLabel gif;
    // End of variables declaration//GEN-END:variables
}
