/*
 * Copyright (C) 2026 tonikelope
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */
package com.tonikelope.coronapoker.table;

import com.tonikelope.coronapoker.core.NewGameTableDraft;
import com.tonikelope.coronapoker.core.game.GameConfigCodecV1;
import java.util.Objects;

/** Commands generated by either renderer and validated by the existing game. */
public sealed interface TableCommand permits TableCommand.Fold,
        TableCommand.CheckOrCall, TableCommand.Bet, TableCommand.AllIn,
        TableCommand.ShowCards, TableCommand.ExitGame,
        TableCommand.StopGame,
        TableCommand.TogglePause, TableCommand.OpenSettings,
        TableCommand.OpenLog, TableCommand.ChangeDeck,
        TableCommand.SelectDeck,
        TableCommand.ToggleImmediateRebuy, TableCommand.SetLastHand,
        TableCommand.SetHandLimit, TableCommand.ApplyGameConfiguration,
        TableCommand.SetBotDifficulty, TableCommand.SetCommunicationRules,
        TableCommand.ForceReconnectPlayers {

    record Fold() implements TableCommand {
    }

    record CheckOrCall() implements TableCommand {
    }

    record Bet(double amount) implements TableCommand {
    }

    record AllIn() implements TableCommand {
    }

    record ShowCards() implements TableCommand {
    }

    record ExitGame() implements TableCommand {
    }

    /** Host-only immediate stop that preserves the table for recovery. */
    record StopGame() implements TableCommand {
    }

    /** Host-only replacement of every remote-human transport connection. */
    record ForceReconnectPlayers() implements TableCommand {
    }

    record TogglePause() implements TableCommand {
    }

    record OpenSettings() implements TableCommand {
    }

    record OpenLog() implements TableCommand {
    }

    record ChangeDeck() implements TableCommand {
    }

    /** Selects one concrete installed presentation deck by identifier. */
    record SelectDeck(String deck) implements TableCommand {

        public SelectDeck {
            Objects.requireNonNull(deck, "deck");
            if (deck.isBlank()) {
                throw new IllegalArgumentException("deck cannot be blank");
            }
        }
    }

    /** Opens the canonical top-up dialog, or cancels an already queued top-up. */
    record ToggleImmediateRebuy() implements TableCommand {
    }

    /** Host-only authoritative scheduling or cancellation of the last hand. */
    record SetLastHand(boolean enabled) implements TableCommand {
    }

    /**
     * Host-only authoritative maximum number of hands. A value of {@code -1}
     * keeps the table unlimited, matching the classic Swing contract.
     */
    record SetHandLimit(int maximumHands) implements TableCommand {

        public SetHandLimit {
            if (maximumHands != -1 && maximumHands < 1) {
                throw new IllegalArgumentException(
                        "maximumHands must be -1 or positive");
            }
        }
    }

    /**
     * Host-only update of the rules that CoronaPoker permits while a table is
     * running. The dealer validates the complete immutable configuration and
     * broadcasts the established Swing-compatible wire commands.
     */
    record ApplyGameConfiguration(
            GameConfigCodecV1.Configuration configuration)
            implements TableCommand {

        public ApplyGameConfiguration {
            Objects.requireNonNull(configuration, "configuration");
        }
    }

    /**
     * Host-local bot strength. Swing deliberately does not broadcast this
     * value because only the host executes bot decisions.
     */
    record SetBotDifficulty(NewGameTableDraft.BotDifficulty difficulty)
            implements TableCommand {

        public SetBotDifficulty {
            Objects.requireNonNull(difficulty, "difficulty");
        }
    }

    /**
     * Host-only global chat rules. These are independent from each player's
     * local TTS/voice blocking preferences and use Swing's established wire
     * commands so mixed frontends remain interoperable.
     */
    record SetCommunicationRules(boolean textToSpeech,
            boolean voiceMessages) implements TableCommand {
    }
}
