/*
 * Copyright (C) 2026 tonikelope
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */
package com.tonikelope.coronapoker.table;

/** Commands generated by either renderer and validated by the existing game. */
public sealed interface TableCommand permits TableCommand.Fold,
        TableCommand.CheckOrCall, TableCommand.Bet, TableCommand.AllIn,
        TableCommand.ShowCards, TableCommand.ExitGame,
        TableCommand.TogglePause, TableCommand.OpenSettings,
        TableCommand.OpenLog, TableCommand.ChangeDeck {

    record Fold() implements TableCommand {
    }

    record CheckOrCall() implements TableCommand {
    }

    record Bet(double amount) implements TableCommand {
    }

    record AllIn() implements TableCommand {
    }

    record ShowCards() implements TableCommand {
    }

    record ExitGame() implements TableCommand {
    }

    record TogglePause() implements TableCommand {
    }

    record OpenSettings() implements TableCommand {
    }

    record OpenLog() implements TableCommand {
    }

    record ChangeDeck() implements TableCommand {
    }
}
