/*
 * Copyright (C) 2020 tonikelope
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.tonikelope.coronapoker;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.LinkedHashMap;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * A named, user-defined blind structure: an ordered ladder of (small blind, big
 * blind) levels the blinds climb through when "increase blinds" is enabled.
 *
 * The built-in default ladder (1-2-3-5 x 10^n, with big blind = 2 x small
 * blind) is generated by {@link #defaultLevels()} and is NOT persisted: it is
 * always available implicitly. Only custom structures are stored, in the shared
 * {@code coronapoker.properties} file via {@link #loadAll()} / {@link #saveAll}.
 *
 * Big blind is independent of small blind (the editor defaults it to 2 x small
 * blind but the user may set any value &gt;= small blind), so the whole pipeline
 * carries the real big blind rather than re-deriving it. Blind values are
 * constrained to multiples of 0.05 (the smallest blind adjustment step); the
 * money engine itself resolves to the cent (0.01) via {@code Helpers.floatClean},
 * so a 0.05-granular blind round-trips exactly through pot and cap logic.
 *
 * Instances are immutable. Persistence and serialization helpers are pure
 * (operate on a passed-in {@link Properties}) so they can be unit-tested without
 * touching the real file.
 *
 * @author tonikelope
 */
public final class BlindStructure {

    private static final Logger LOGGER = Logger.getLogger(BlindStructure.class.getName());

    // Persistence keys in coronapoker.properties. Custom structures are stored
    // by index (never by name) so a name may contain any printable character
    // without clashing with the key grammar.
    public static final String PROP_COUNT = "blind_structures.count";
    public static final String PROP_PREFIX = "blind_structure.";

    public static final int MAX_STRUCTURES = 64;
    public static final int MAX_LEVELS = 64;
    public static final int MAX_NAME_LENGTH = 40;
    public static final double MIN_BLIND = 0.05;
    // Las ciegas se ajustan en pasos de 0.05 (0.25/0.30/0.35 sí; 0.33/0.04 no).
    // El motor del dinero trabaja por debajo en céntimos (0.01), pero la unidad
    // de ajuste de ciegas es 0.05. Ver Helpers.floatClean (resolución del motor).
    public static final double BLIND_STEP = 0.05;
    public static final double MAX_BLIND = 10_000_000;

    // Validation error codes (also i18n keys). null = valid.
    public static final String ERR_NAME_EMPTY = "blinds.err_name_empty";
    public static final String ERR_NAME_TOO_LONG = "blinds.err_name_too_long";
    public static final String ERR_NAME_CHARS = "blinds.err_name_chars";
    public static final String ERR_NO_LEVELS = "blinds.err_no_levels";
    public static final String ERR_TOO_MANY_LEVELS = "blinds.err_too_many_levels";
    public static final String ERR_VALUE_RANGE = "blinds.err_value_range";
    public static final String ERR_PRECISION = "blinds.err_precision";
    public static final String ERR_BB_LT_SB = "blinds.err_bb_lt_sb";
    public static final String ERR_NOT_INCREASING = "blinds.err_not_increasing";

    private final String name;
    private final double[][] levels; // [i] = {small_blind, big_blind} (double money)

    /**
     * @param name non-empty, trimmed, printable, at most {@link #MAX_NAME_LENGTH}
     * @param levels ordered {sb, bb} pairs; validated, defensively copied
     * @throws IllegalArgumentException if name or levels are invalid
     */
    public BlindStructure(String name, double[][] levels) {
        String trimmed = name == null ? "" : name.trim();
        String name_err = validateName(trimmed);
        if (name_err != null) {
            throw new IllegalArgumentException(name_err);
        }
        String levels_err = validateLevels(levels);
        if (levels_err != null) {
            throw new IllegalArgumentException(levels_err);
        }
        this.name = trimmed;
        this.levels = deepCopy(levels);
    }

    public String getName() {
        return name;
    }

    /**
     * @return a defensive copy of the {sb, bb} ladder
     */
    public double[][] getLevels() {
        return deepCopy(levels);
    }

    public int size() {
        return levels.length;
    }

    private static double[][] deepCopy(double[][] src) {
        double[][] out = new double[src.length][];
        for (int i = 0; i < src.length; i++) {
            out[i] = new double[]{src[i][0], src[i][1]};
        }
        return out;
    }

    // ----- Validation ---------------------------------------------------------

    /**
     * Validates the structure name format (uniqueness is the caller's concern).
     *
     * @return null if valid, otherwise an i18n error key
     */
    public static String validateName(String name) {
        String trimmed = name == null ? "" : name.trim();
        if (trimmed.isEmpty()) {
            return ERR_NAME_EMPTY;
        }
        if (trimmed.length() > MAX_NAME_LENGTH) {
            return ERR_NAME_TOO_LONG;
        }
        // No control characters: they would corrupt the .properties value (which
        // is single-line) and break round-tripping.
        for (int i = 0; i < trimmed.length(); i++) {
            if (Character.isISOControl(trimmed.charAt(i))) {
                return ERR_NAME_CHARS;
            }
        }
        return null;
    }

    /**
     * Validates a {sb, bb} ladder: at least one level, each value in range and
     * at one-decimal resolution, big blind &gt;= small blind, and both columns
     * strictly increasing from one level to the next.
     *
     * @return null if valid, otherwise an i18n error key
     */
    public static String validateLevels(double[][] levels) {
        if (levels == null || levels.length == 0) {
            return ERR_NO_LEVELS;
        }
        if (levels.length > MAX_LEVELS) {
            return ERR_TOO_MANY_LEVELS;
        }
        for (int i = 0; i < levels.length; i++) {
            if (levels[i] == null || levels[i].length != 2) {
                return ERR_NO_LEVELS;
            }
            double sb = levels[i][0];
            double bb = levels[i][1];
            if (sb < MIN_BLIND || bb < MIN_BLIND || sb > MAX_BLIND || bb > MAX_BLIND
                    || Double.isNaN(sb) || Double.isNaN(bb)) {
                return ERR_VALUE_RANGE;
            }
            if (!isBlindStep(sb) || !isBlindStep(bb)) {
                return ERR_PRECISION;
            }
            if (bb < sb) {
                return ERR_BB_LT_SB;
            }
            if (i > 0 && (sb <= levels[i - 1][0] || bb <= levels[i - 1][1])) {
                return ERR_NOT_INCREASING;
            }
        }
        return null;
    }

    // A valid blind value: a whole multiple of the 0.05 blind step (20*v must be
    // an integer). So 0.25/0.30/0.35 are accepted, 0.33/0.04 are not.
    private static boolean isBlindStep(double v) {
        double scaled = v * 20;
        return Math.abs(scaled - Math.round(scaled)) < 0.01f;
    }

    // ----- Serialization (levels <-> string) ----------------------------------

    /**
     * Serializes the ladder as {@code sb/bb,sb/bb,...} with a '.' decimal
     * separator (locale-independent storage form).
     */
    public String levelsToString() {
        return levelsToString(levels);
    }

    public static String levelsToString(double[][] levels) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < levels.length; i++) {
            if (i > 0) {
                sb.append(',');
            }
            sb.append(trimDouble(levels[i][0])).append('/').append(trimDouble(levels[i][1]));
        }
        return sb.toString();
    }

    // Compact storage form: drop a trailing ".0" so whole blinds read "25" not
    // "25.0", but keep one decimal when present ("0.5").
    private static String trimDouble(double v) {
        if (v == Math.rint(v)) {
            return String.valueOf((long) v);
        }
        return String.valueOf(v);
    }

    /**
     * Parses the {@link #levelsToString()} storage form back into a ladder.
     *
     * @throws IllegalArgumentException if the text is malformed
     */
    public static double[][] parseLevels(String csv) {
        if (csv == null || csv.trim().isEmpty()) {
            throw new IllegalArgumentException(ERR_NO_LEVELS);
        }
        String[] tokens = csv.trim().split(",");
        double[][] out = new double[tokens.length][];
        for (int i = 0; i < tokens.length; i++) {
            String[] pair = tokens[i].trim().split("/");
            if (pair.length != 2) {
                throw new IllegalArgumentException(ERR_NO_LEVELS);
            }
            try {
                out[i] = new double[]{Double.parseDouble(pair[0].trim()), Double.parseDouble(pair[1].trim())};
            } catch (NumberFormatException ex) {
                throw new IllegalArgumentException(ERR_VALUE_RANGE);
            }
        }
        return out;
    }

    /**
     * Parses AND fully validates a serialized ladder. Unlike {@link #parseLevels}
     * (grammar only), this also enforces {@link #validateLevels} (range, 0.05
     * step, bb &gt;= sb, strictly increasing). Used at the recover/wire ingestion
     * points so a persisted or broadcast ladder is never fed to the engine
     * without the same checks the editor applies — the callers catch the
     * exception and fall back to the default ladder.
     *
     * @throws IllegalArgumentException if the grammar is malformed or the ladder
     *                                  is logically invalid
     */
    public static double[][] parseValidatedLevels(String csv) {
        double[][] levels = parseLevels(csv);
        String err = validateLevels(levels);
        if (err != null) {
            throw new IllegalArgumentException("Invalid blind structure: " + err);
        }
        return levels;
    }

    // ----- Built-in default ladder --------------------------------------------

    /**
     * The built-in 1-2-3-5 x 10^n ladder with big blind = 2 x small blind, from
     * 0.1/0.2 up to 5,000,000/10,000,000 (the {@link #MAX_BLIND} ceiling). These
     * are exactly the levels offered by the new-game / edit-blinds combo and the
     * ladder walked by the default (no custom structure) escalation in
     * {@code Crupier}. A long, aggressive-doubling game climbs many levels, so the
     * ladder runs all the way to the money engine's cap before the blinds finally
     * stop rising. Returned as a fresh array on each call.
     */
    public static double[][] defaultLevels() {
        double[] sbs = {
            0.1, 0.2, 0.3, 0.5,
            1, 2, 3, 5,
            10, 20, 30, 50,
            100, 200, 300, 500,
            1000, 2000, 3000, 5000,
            10000, 20000, 30000, 50000,
            100000, 200000, 300000, 500000,
            1000000, 2000000, 3000000, 5000000
        };
        double[][] out = new double[sbs.length][];
        for (int i = 0; i < sbs.length; i++) {
            out[i] = new double[]{sbs[i], sbs[i] * 2};
        }
        return out;
    }

    // ----- Combo display format -----------------------------------------------

    /**
     * Renders a blind value for the "small / big" combo items AND the level
     * matcher, so a structure's current level is always found and the item
     * round-trips through the {@code Double.parseDouble} parsers. Unlike
     * {@code Helpers.money2String} it never abbreviates {@code >= 1000} as "K"
     * (which the parsers cannot read) and never truncates a fractional value to
     * an integer. Reproduces the legacy ladder strings exactly for the default
     * levels (e.g. {@code 0.1 -> "0,10"}, {@code 1 -> "1"}, {@code 1000 -> "1000"}).
     */
    public static String formatLevelValue(double v) {
        if (v < 1000) {
            // money2String never abbreviates below 1000 and yields the legacy
            // sub-1 forms ("0,10","0,25","0,50") and whole forms ("1","500").
            return Helpers.money2String(v);
        }
        if (v == Math.rint(v)) {
            return String.valueOf((long) v);
        }
        String s = new java.math.BigDecimal(v).setScale(2, java.math.RoundingMode.HALF_UP)
                .stripTrailingZeros().toPlainString();
        return "es".equals(GameFrame.LANGUAGE.toLowerCase()) ? s.replace('.', ',') : s;
    }

    /**
     * The {@code "small / big"} combo string for one level, using
     * {@link #formatLevelValue}.
     */
    public static String formatLevel(double sb, double bb) {
        return formatLevelValue(sb) + " / " + formatLevelValue(bb);
    }

    // ----- Escalation walk (pure, for the Crupier custom path) ----------------

    // Money is represented at cent resolution (Helpers.floatClean, HALF_UP). Two
    // blind values are the same ladder level iff they round to the same cent.
    // Validated ladders have strictly increasing small blinds (>= 0.05 apart), so
    // this key is unique per level and distinguishes e.g. 0.25 from 0.30.
    private static int cents(double v) {
        return (int) Math.round(v * 100);
    }

    /**
     * Index of the level whose small blind matches {@code sb} at the game's cent
     * money resolution, or -1 if none.
     */
    public static int indexOfLevel(double[][] structure, double sb) {
        if (structure == null) {
            return -1;
        }
        int key = cents(sb);
        for (int i = 0; i < structure.length; i++) {
            if (cents(structure[i][0]) == key) {
                return i;
            }
        }
        return -1;
    }

    /**
     * The {sb, bb} level immediately above the one matching {@code currentSb},
     * or null when the current blind is the top level (no further escalation) or
     * is not on this ladder at all. Returned as a fresh array.
     */
    public static double[] nextLevel(double[][] structure, double currentSb) {
        int idx = indexOfLevel(structure, currentSb);
        if (idx < 0 || idx + 1 >= structure.length) {
            return null;
        }
        return new double[]{structure[idx + 1][0], structure[idx + 1][1]};
    }

    // ----- Registry persistence -----------------------------------------------

    /**
     * Reads all custom structures from the given properties, preserving order.
     * Malformed or invalid entries (and duplicate names) are skipped, never
     * fatal, so a hand-corrupted properties file can never block startup.
     *
     * @return name -&gt; structure, in stored order
     */
    public static LinkedHashMap<String, BlindStructure> readFrom(Properties props) {
        LinkedHashMap<String, BlindStructure> out = new LinkedHashMap<>();
        if (props == null) {
            return out;
        }
        int count;
        try {
            count = Integer.parseInt(props.getProperty(PROP_COUNT, "0").trim());
        } catch (NumberFormatException ex) {
            return out;
        }
        count = Math.max(0, Math.min(count, MAX_STRUCTURES));
        for (int i = 0; i < count; i++) {
            String name = props.getProperty(PROP_PREFIX + i + ".name");
            String levels_csv = props.getProperty(PROP_PREFIX + i + ".levels");
            if (name == null || levels_csv == null) {
                continue;
            }
            try {
                BlindStructure bs = new BlindStructure(name, parseLevels(levels_csv));
                if (!out.containsKey(bs.getName())) {
                    out.put(bs.getName(), bs);
                }
            } catch (IllegalArgumentException ex) {
                LOGGER.log(Level.WARNING, "Skipping invalid stored blind structure at index {0}: {1}",
                        new Object[]{i, ex.getMessage()});
            }
        }
        return out;
    }

    /**
     * Writes the given structures to the properties, replacing any previously
     * stored set (so renames and deletions persist). Does NOT flush to disk.
     */
    public static void writeTo(Properties props, Collection<BlindStructure> structures) {
        if (props == null) {
            return;
        }
        // Clean slate: drop every previously stored structure key.
        ArrayList<String> stale = new ArrayList<>();
        for (String key : props.stringPropertyNames()) {
            if (key.startsWith(PROP_PREFIX) || key.equals(PROP_COUNT)) {
                stale.add(key);
            }
        }
        for (String key : stale) {
            props.remove(key);
        }
        int i = 0;
        for (BlindStructure bs : structures) {
            if (i >= MAX_STRUCTURES) {
                LOGGER.log(Level.WARNING, "Truncating stored blind structures to the {0} cap", MAX_STRUCTURES);
                break;
            }
            props.setProperty(PROP_PREFIX + i + ".name", bs.getName());
            props.setProperty(PROP_PREFIX + i + ".levels", bs.levelsToString());
            i++;
        }
        props.setProperty(PROP_COUNT, String.valueOf(i));
    }

    /**
     * Loads custom structures from the shared {@code coronapoker.properties}.
     */
    public static LinkedHashMap<String, BlindStructure> loadAll() {
        return readFrom(Helpers.PROPERTIES);
    }

    /**
     * Persists custom structures to the shared {@code coronapoker.properties}
     * and flushes to disk.
     */
    public static synchronized void saveAll(Collection<BlindStructure> structures) {
        writeTo(Helpers.PROPERTIES, structures);
        Helpers.savePropertiesFile();
    }

    // ----- equals / hashCode (value semantics for tests and dedup) ------------

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof BlindStructure)) {
            return false;
        }
        BlindStructure other = (BlindStructure) o;
        return name.equals(other.name) && Arrays.deepEquals(levels, other.levels);
    }

    @Override
    public int hashCode() {
        return 31 * name.hashCode() + Arrays.deepHashCode(levels);
    }

    @Override
    public String toString() {
        return "BlindStructure[" + name + ": " + levelsToString() + "]";
    }
}
