/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tonikelope.coronapoker;

import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.text.BadLocationException;

/**
 *
 * @author tonikelope
 */
public class EmojiPanel extends javax.swing.JPanel {

    /**
     * Creates new form EmojiPanel
     */
    public EmojiPanel() {
        initComponents();

        for (int i = 1; i <= 131; i++) {

            JLabel label = new JLabel();

            label.setCursor(new Cursor(Cursor.HAND_CURSOR));

            label.setIcon(new ImageIcon(getClass().getResource("/images/emoji_chat/" + i + ".png")));

            final int j = i;

            label.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    try {

                        WaitingRoomFrame.getInstance().getChat_box().getDocument().insertString(WaitingRoomFrame.getInstance().getChat_box().getCaretPosition(), " #" + j + "# ", null);

                    } catch (BadLocationException ex) {
                        Logger.getLogger(EmojiPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            });

            add(label);
        }

        revalidate();

        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setFocusable(false);
        setRequestFocusEnabled(false);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
