/*
 * Copyright (C) 2026 tonikelope
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.tonikelope.coronapoker;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Arrays;
import java.util.Comparator;
import java.util.List;

/**
 * EC-Identity v1 (commit 4): hand-state hash chain (H_t ratchet).
 *
 * <p>Each peer keeps an instance of this class for the current hand. The chain
 * is seeded by {@link #start(byte[], List, byte[])} after the SRA cascade is
 * complete (so the deck commitment is final) and absorbs every canonical action
 * record produced by {@link CanonicalActionRecord#encode}. At the end of the
 * hand all peers compare their {@code H_final} as part of the consensus check
 * implemented in commit 6.
 *
 * <p>The math, from {@code docs/ec-identity-spec.md} §5:
 *
 * <pre>
 *   H_0 = SHA-256(
 *           "HAND_V1\0"                        // 8-byte domain separator
 *           || HAND_ID                         // 16 random bytes from host
 *           || uint8(num_players)              // 1 byte
 *           || sorted_player_ids_concat        // 32 × N, lexicographic order
 *           || SHA-256(cascaded_deck_bytes)    // 32-byte deck commitment
 *         )
 *
 *   H_t = SHA-256(record_t || sig_t)
 * </pre>
 *
 * <p>The signature in the ratchet provides signature-level non-repudiation on
 * top of the cross-peer divergence detection. Phase 3 extends the same ratchet
 * to host-signed community-card announces (ACTION_COMMUNITY records), closing
 * the cross-recipient fork attack where the host could announce different
 * boards to different peers without leaving evidence in H_t.
 *
 * <p>Instances are NOT thread-safe. Callers serialize access through the
 * dealer's per-hand control flow.
 */
public final class HandStateChain {

    /**
     * Master debug switch. When {@code true}, every peer broadcasts
     * {@code H_CHECK # nick # h_t_b64} after absorbing each action so divergent
     * chains can be spotted live in the log instead of only at hand close.
     * Adds wire chatter, leaks intermediate state correlated with public
     * actions, and is therefore <strong>never enabled in release builds</strong>.
     */
    public static final boolean DEBUG_HANDCHAIN = false;

    /**
     * Domain separator for the initial state. The terminator NUL byte prevents
     * any accidental collision with strings that happen to start with
     * {@code "HAND_V1"}.
     */
    public static final byte[] DOMAIN_HAND_V1 = "HAND_V1\0".getBytes(StandardCharsets.UTF_8);

    /**
     * Domain separator for HAND_V2, which additionally binds every peer's per-hand
     * public key commitments (K_pocket, K_community) into H_0 for verifiable dealing.
     */
    public static final byte[] DOMAIN_HAND_V2 = "HAND_V2\0".getBytes(StandardCharsets.UTF_8);

    /** Length in bytes of {@code H_t}. */
    public static final int HASH_BYTES = 32;

    private final byte[] handId;
    private byte[] currentHash;
    private int absorbedActions;

    private HandStateChain(byte[] handId, byte[] h0) {
        this.handId = handId.clone();
        this.currentHash = h0;
        this.absorbedActions = 0;
    }

    /**
     * Creates the chain in its initial state for a new hand. Every peer must
     * produce a byte-identical {@code H_0} from the same inputs.
     *
     * @param handId          16 random bytes generated by the host at hand start
     * @param playerIds       canonical player ids of every peer in the
     *                        crypto-ring (32 bytes each, see
     *                        {@link CanonicalActionRecord#playerIdFromNick})
     * @param cascadedDeck    the SRA-cascaded deck bytes after every peer has
     *                        applied their lock and shuffle; this is the value
     *                        that the host broadcasts as the MEGAPACKET
     * @return a fresh chain initialised at {@code H_0}
     */
    public static HandStateChain start(byte[] handId, List<byte[]> playerIds, byte[] cascadedDeck) {
        if (handId == null || handId.length != CanonicalActionRecord.HAND_ID_BYTES) {
            throw new IllegalArgumentException("handId must be "
                    + CanonicalActionRecord.HAND_ID_BYTES + " bytes");
        }
        if (playerIds == null || playerIds.isEmpty()) {
            throw new IllegalArgumentException("playerIds required");
        }
        if (playerIds.size() > 255) {
            throw new IllegalArgumentException("num_players exceeds uint8: " + playerIds.size());
        }
        if (cascadedDeck == null || cascadedDeck.length == 0) {
            throw new IllegalArgumentException("cascadedDeck required");
        }

        // Sort player ids lexicographically as 32-byte unsigned integers so
        // join order does not affect H_0. Defensive copy so the caller's list
        // is not mutated.
        byte[][] sorted = new byte[playerIds.size()][];
        for (int i = 0; i < playerIds.size(); i++) {
            byte[] pid = playerIds.get(i);
            if (pid == null || pid.length != HASH_BYTES) {
                throw new IllegalArgumentException(
                        "playerIds[" + i + "] must be " + HASH_BYTES + " bytes");
            }
            sorted[i] = pid.clone();
        }
        Arrays.sort(sorted, UNSIGNED_LEX_ORDER);

        byte[] deckCommitment = sha256(cascadedDeck);

        // Concatenate everything that goes into H_0 and hash once. The fixed
        // section sizes (8 + 16 + 1 + 32 + 32 × N) make this allocation
        // exact, no resizing.
        int totalLen = DOMAIN_HAND_V1.length
                + CanonicalActionRecord.HAND_ID_BYTES
                + 1
                + (HASH_BYTES * sorted.length)
                + HASH_BYTES;
        byte[] preimage = new byte[totalLen];
        int p = 0;
        System.arraycopy(DOMAIN_HAND_V1, 0, preimage, p, DOMAIN_HAND_V1.length);
        p += DOMAIN_HAND_V1.length;
        System.arraycopy(handId, 0, preimage, p, CanonicalActionRecord.HAND_ID_BYTES);
        p += CanonicalActionRecord.HAND_ID_BYTES;
        preimage[p++] = (byte) (sorted.length & 0xFF);
        for (byte[] pid : sorted) {
            System.arraycopy(pid, 0, preimage, p, HASH_BYTES);
            p += HASH_BYTES;
        }
        System.arraycopy(deckCommitment, 0, preimage, p, HASH_BYTES);

        return new HandStateChain(handId, sha256(preimage));
    }

    /**
     * HAND_V2 initial state: like {@link #start} but additionally binds every peer's
     * per-hand public commitments K_pocket = k_pocket*B and K_community =
     * k_community*B (Ristretto255 encodings, 32 bytes each) into H_0, so the
     * verifiable-dealing chain (Phase 4) can be checked against keys no party can
     * forge after the fact. The three lists are parallel (index i belongs to
     * playerIds[i]); peers are sorted by player id so join order does not affect H_0.
     *
     * <pre>
     *   H_0 = SHA-256( "HAND_V2\0" || HAND_ID || uint8(N)
     *                  || for each peer (sorted by id): id(32) || K_pocket(32) || K_community(32)
     *                  || SHA-256(cascaded_deck) )
     * </pre>
     */
    public static HandStateChain startV2(byte[] handId, List<byte[]> playerIds,
            List<byte[]> kPocketCommits, List<byte[]> kCommunityCommits, byte[] cascadedDeck) {
        if (handId == null || handId.length != CanonicalActionRecord.HAND_ID_BYTES) {
            throw new IllegalArgumentException("handId must be "
                    + CanonicalActionRecord.HAND_ID_BYTES + " bytes");
        }
        if (playerIds == null || playerIds.isEmpty()) {
            throw new IllegalArgumentException("playerIds required");
        }
        int n = playerIds.size();
        if (n > 255) {
            throw new IllegalArgumentException("num_players exceeds uint8: " + n);
        }
        if (kPocketCommits == null || kCommunityCommits == null
                || kPocketCommits.size() != n || kCommunityCommits.size() != n) {
            throw new IllegalArgumentException("commitment lists must match playerIds size");
        }
        if (cascadedDeck == null || cascadedDeck.length == 0) {
            throw new IllegalArgumentException("cascadedDeck required");
        }

        // Pack each peer as id(32) || K_pocket(32) || K_community(32) and sort by the
        // leading id bytes (ids are unique, so the id prefix decides the order).
        byte[][] packed = new byte[n][];
        for (int i = 0; i < n; i++) {
            byte[] pid = playerIds.get(i);
            byte[] kp = kPocketCommits.get(i);
            byte[] kc = kCommunityCommits.get(i);
            if (pid == null || pid.length != HASH_BYTES
                    || kp == null || kp.length != HASH_BYTES
                    || kc == null || kc.length != HASH_BYTES) {
                throw new IllegalArgumentException(
                        "peer " + i + ": id and commitments must be " + HASH_BYTES + " bytes");
            }
            byte[] row = new byte[HASH_BYTES * 3];
            System.arraycopy(pid, 0, row, 0, HASH_BYTES);
            System.arraycopy(kp, 0, row, HASH_BYTES, HASH_BYTES);
            System.arraycopy(kc, 0, row, HASH_BYTES * 2, HASH_BYTES);
            packed[i] = row;
        }
        Arrays.sort(packed, (x, y) -> Arrays.compareUnsigned(x, y));

        byte[] deckCommitment = sha256(cascadedDeck);
        int totalLen = DOMAIN_HAND_V2.length
                + CanonicalActionRecord.HAND_ID_BYTES
                + 1
                + (HASH_BYTES * 3 * n)
                + HASH_BYTES;
        byte[] preimage = new byte[totalLen];
        int p = 0;
        System.arraycopy(DOMAIN_HAND_V2, 0, preimage, p, DOMAIN_HAND_V2.length);
        p += DOMAIN_HAND_V2.length;
        System.arraycopy(handId, 0, preimage, p, CanonicalActionRecord.HAND_ID_BYTES);
        p += CanonicalActionRecord.HAND_ID_BYTES;
        preimage[p++] = (byte) (n & 0xFF);
        for (byte[] row : packed) {
            System.arraycopy(row, 0, preimage, p, row.length);
            p += row.length;
        }
        System.arraycopy(deckCommitment, 0, preimage, p, HASH_BYTES);

        return new HandStateChain(handId, sha256(preimage));
    }

    /**
     * Returns this hand's {@code HAND_ID} (defensive copy). The caller should
     * feed exactly these bytes into every {@link CanonicalActionRecord#encode}
     * call for this hand.
     */
    public byte[] getHandId() {
        return handId.clone();
    }

    /**
     * Returns the current chain hash {@code H_t} (defensive copy).
     */
    public byte[] getCurrentHash() {
        return currentHash.clone();
    }

    /** Number of action records absorbed since {@link #start(byte[], List, byte[])}. */
    public int getAbsorbedActions() {
        return absorbedActions;
    }

    /** Length in bytes of an Ed25519 signature (§4.4). */
    public static final int SIG_BYTES = 64;

    /**
     * Absorbs a record-only action (no signature) into the chain. Used by commit-4
     * callers and unit tests for the bare ratchet. The first 32 bytes of the record
     * must equal the chain's current {@code H_t}; this is the point of the chain.
     *
     * <p>Commit 4 ratchet: {@code H_{t+1} = SHA-256(record)}.
     *
     * @return the new {@code H_{t+1}} (defensive copy)
     */
    public byte[] absorb(byte[] record) {
        validateRecord(record);
        this.currentHash = sha256(record);
        this.absorbedActions++;
        return getCurrentHash();
    }

    /**
     * Absorbs a signed action into the chain (commit 5). The signature bytes are
     * concatenated to the record before hashing, so verifying {@code H_final}
     * implicitly verifies that every constituent action was accompanied by some
     * signature. Whether that signature was VALID is checked separately by the
     * caller (§4.5 receiver rule) — invalid sigs are absorbed anyway so that
     * divergence is detectable at hand close.
     *
     * <p>Commit 5 ratchet: {@code H_{t+1} = SHA-256(record || sig)}.
     *
     * @return the new {@code H_{t+1}} (defensive copy)
     */
    public byte[] absorb(byte[] record, byte[] sig) {
        validateRecord(record);
        if (sig == null || sig.length != SIG_BYTES) {
            throw new IllegalArgumentException("sig must be " + SIG_BYTES + " bytes");
        }
        byte[] preimage = new byte[record.length + sig.length];
        System.arraycopy(record, 0, preimage, 0, record.length);
        System.arraycopy(sig, 0, preimage, record.length, sig.length);
        this.currentHash = sha256(preimage);
        this.absorbedActions++;
        return getCurrentHash();
    }

    private void validateRecord(byte[] record) {
        if (record == null || record.length != CanonicalActionRecord.RECORD_BYTES) {
            throw new IllegalArgumentException("record must be "
                    + CanonicalActionRecord.RECORD_BYTES + " bytes");
        }
        for (int i = 0; i < HASH_BYTES; i++) {
            if (record[CanonicalActionRecord.OFFSET_PREV_H + i] != currentHash[i]) {
                throw new IllegalStateException(
                        "record.PREV_H does not match the chain's current H_t");
            }
        }
    }

    /**
     * Lexicographic comparator over unsigned 32-byte arrays (treats bytes as
     * {@code 0..255}, not signed Java bytes). Needed because Java's default
     * byte comparison is signed and would put {@code 0x80..0xFF} bytes before
     * {@code 0x00..0x7F}.
     */
    private static final Comparator<byte[]> UNSIGNED_LEX_ORDER = (a, b) -> {
        int len = Math.min(a.length, b.length);
        for (int i = 0; i < len; i++) {
            int diff = (a[i] & 0xFF) - (b[i] & 0xFF);
            if (diff != 0) {
                return diff;
            }
        }
        return a.length - b.length;
    };

    private static byte[] sha256(byte[] data) {
        try {
            return MessageDigest.getInstance("SHA-256").digest(data);
        } catch (NoSuchAlgorithmException ex) {
            throw new RuntimeException("SHA-256 unavailable", ex);
        }
    }
}
