/*
 * Copyright (C) 2020 tonikelope
 _              _ _        _                  
| |_ ___  _ __ (_) | _____| | ___  _ __   ___ 
| __/ _ \| '_ \| | |/ / _ \ |/ _ \| '_ \ / _ \
| || (_) | | | | |   <  __/ | (_) | |_) |  __/
 \__\___/|_| |_|_|_|\_\___|_|\___/| .__/ \___|
 ____    ___  ____    ___  
|___ \  / _ \|___ \  / _ \ 
  __) || | | | __) || | | |
 / __/ | |_| |/ __/ | |_| |
|_____| \___/|_____| \___/ 

https://github.com/tonikelope/coronapoker
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.tonikelope.coronapoker;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.TexturePaint;
import java.awt.geom.Rectangle2D;
import java.awt.image.BufferedImage;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author tonikelope
 */
public class InitPanel extends javax.swing.JLayeredPane {

    protected volatile TexturePaint tp = null;
    protected volatile boolean invalidate = false;
    protected final Object paint_lock = new Object();
    private static TexturePaint CACHED_TAPETE = null;

    /**
     * Creates new form InitPanel
     */
    public InitPanel() {
        // 1. Inicialización rápida de componentes UI
        Helpers.GUIRunAndWait(this::initComponents);

        // 2. Carga asíncrona de la textura
        // No bloqueamos el constructor, dejamos que el tapete aparezca cuando esté listo
        if (CACHED_TAPETE != null && !GameFrame.COLOR_TAPETE.endsWith("*")) {
            this.tp = CACHED_TAPETE;
        } else {
            updateTexture(); // El método que creamos antes, que usa un hilo separado
        }

        // 3. Listener de redimensionado (se mantiene igual, es eficiente)
        addComponentListener(new ComponentResizeEndListener() {
            @Override
            public void resizeTimedOut() {
                if (GameFrame.COLOR_TAPETE.endsWith("*")) {
                    refresh();
                }
            }
        });
    }

    public void refresh() {
        this.invalidate = true;
        updateTexture(); // Start the background loading process
    }

    private void updateTexture() {
        Helpers.threadRun(() -> {
            synchronized (paint_lock) {
                try {
                    BufferedImage tile;
                    int w = Math.max(getWidth(), 1); // Evita 0
                    int h = Math.max(getHeight(), 1);

                    if (GameFrame.COLOR_TAPETE.endsWith("*") && Init.I1 != null) {
                        Image scaled = Init.I1.getScaledInstance(w, h, Image.SCALE_SMOOTH);
                        tile = Helpers.toBufferedImage(scaled);
                    } else {
                        String resPath = "/images/tapete_" + GameFrame.COLOR_TAPETE + ".jpg";
                        tile = ImageIO.read(getClass().getResourceAsStream(resPath));
                    }

                    Rectangle2D anchor = new Rectangle2D.Double(0, 0, tile.getWidth(), tile.getHeight());
                    this.tp = new TexturePaint(tile, anchor);

                    // --- AQUÍ SE ACTIVA EL CACHÉ ---
                    if (!GameFrame.COLOR_TAPETE.endsWith("*")) {
                        CACHED_TAPETE = this.tp;
                    }

                    this.invalidate = false;
                    Helpers.GUIRun(this::repaint);

                } catch (Exception ex) {
                    Logger.getLogger(InitPanel.class.getName()).log(Level.SEVERE, "Error loading texture", ex);
                }
            }
        });
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); // Important to maintain transparency and child components

        if (tp != null) {
            Graphics2D g2d = (Graphics2D) g;
            // Optimization: Use the current paint (texture) and fill the area
            g2d.setPaint(tp);
            g2d.fillRect(0, 0, getWidth(), getHeight());
        } else {
            // Optional: Fallback color while texture is loading
            g.setColor(java.awt.Color.DARK_GRAY);
            g.fillRect(0, 0, getWidth(), getHeight());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
