/*
 * Copyright (C) 2020 tonikelope
 _              _ _        _                  
| |_ ___  _ __ (_) | _____| | ___  _ __   ___ 
| __/ _ \| '_ \| | |/ / _ \ |/ _ \| '_ \ / _ \
| || (_) | | | | |   <  __/ | (_) | |_) |  __/
 \__\___/|_| |_|_|_|\_\___|_|\___/| .__/ \___|
 ____    ___  ____    ___  
|___ \  / _ \|___ \  / _ \ 
  __) || | | | __) || | | |
 / __/ | |_| |/ __/ | |_| |
|_____| \___/|_____| \___/ 

https://github.com/tonikelope/coronapoker
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.tonikelope.coronapoker;

import com.tonikelope.coronapoker.Helpers.HandScrollListener;
import java.awt.Color;
import java.io.IOException;
import java.awt.Font;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author tonikelope
 */
public class RadarLogDialog extends javax.swing.JDialog {

    /**
     * Creates new form AntiCheatLogDialog
     */
    public RadarLogDialog(java.awt.Frame parent, boolean modal, String path, long timestamp) {
        super(parent, modal);
        initComponents();

        setTitle(Init.WINDOW_TITLE + " - RADAR");

        screenshot.setIcon(new ImageIcon(path + ".jpg"));

        boolean vm = false;

        try {

            String proc = Files.readString(Paths.get(path + ".log"));

            vm = (proc.charAt(0) == '*');

            procesos.setText(vm?proc.substring(1).trim():proc.trim());

            procesos.setCaretPosition(0);
        } catch (IOException ex) {
            Logger.getLogger(RadarLogDialog.class.getName()).log(Level.SEVERE, null, ex);
        }

        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);
        jScrollPane1.getHorizontalScrollBar().setUnitIncrement(16);
        jScrollPane2.getVerticalScrollBar().setUnitIncrement(16);
        jScrollPane2.getHorizontalScrollBar().setUnitIncrement(16);

        HandScrollListener scrollListener = new HandScrollListener(screenshot);
        jScrollPane1.getViewport().addMouseMotionListener(scrollListener);
        jScrollPane1.getViewport().addMouseListener(scrollListener);

        setSize(Math.round(parent.getWidth() * 0.9f), Math.round(parent.getHeight() * 0.9f));

        setPreferredSize(getSize());

        Font original_dialog_font = procesos.getFont();

        Helpers.JTextFieldRegularPopupMenu.addTo(procesos);

        Helpers.updateFonts(this, Helpers.GUI_FONT, null);

        procesos.setFont(original_dialog_font);

        if (vm) {
            jLabel1.setBackground(Color.red);
            jLabel1.setForeground(Color.WHITE);
            jLabel1.setText("AVISO: ESTE USUARIO PARECE ESTAR EJECUTANDO CORONAPOKER DENTRO DE UNA MÁQUINA VIRTUAL, LO QUE RESTA UTILIDAD ESTE INFORME Y ES MUY SOSPECHOSO.");
        }

        Helpers.translateComponents(this, false);

        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        screenshot = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        procesos = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        screenshot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        screenshot.setDoubleBuffered(true);
        jScrollPane1.setViewportView(screenshot);

        procesos.setEditable(false);
        procesos.setBackground(new java.awt.Color(204, 204, 204));
        procesos.setColumns(20);
        procesos.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        procesos.setRows(5);
        procesos.setDoubleBuffered(true);
        jScrollPane2.setViewportView(procesos);

        jLabel1.setBackground(new java.awt.Color(255, 255, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ATENCIÓN: toda esta información debe ser revisada y contrastada manualmente para concluir si el jugador ha hecho trampas.");
        jLabel1.setDoubleBuffered(true);
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addComponent(jScrollPane1)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea procesos;
    private javax.swing.JLabel screenshot;
    // End of variables declaration//GEN-END:variables
}
