/*
 * Copyright (C) 2020 tonikelope
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.tonikelope.coronapoker;

import javax.swing.JLabel;

/**
 *
 * @author tonikelope
 */
public class RecoverDialog extends javax.swing.JDialog {

    /**
     * Creates new form Mantenimiento
     */
    public RecoverDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        RecoverDialog tthis = this;

        Helpers.GUIRunAndWait(new Runnable() {
            public void run() {
                initComponents();
                Helpers.updateFonts(tthis, Helpers.GUI_FONT, null);
                Helpers.translateComponents(tthis, false);
                pack();
            }
        });
    }

    public JLabel getMantenimiento() {
        return mantenimiento;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mantenimiento = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        mantenimiento1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        mantenimiento.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        mantenimiento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mantenimiento.setText("RECUPERANDO TIMBA");
        mantenimiento.setDoubleBuffered(true);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mantenimiento.png"))); // NOI18N
        jLabel1.setDoubleBuffered(true);

        mantenimiento1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        mantenimiento1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mantenimiento1.setText("POR FAVOR, ESPERA");
        mantenimiento1.setDoubleBuffered(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mantenimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mantenimiento1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mantenimiento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mantenimiento1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel mantenimiento;
    private javax.swing.JLabel mantenimiento1;
    // End of variables declaration//GEN-END:variables
}
