/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tonikelope.coronapoker;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JLabel;

/**
 *
 * @author tonikelope
 */
public class TTSNotifyPanel extends javax.swing.JPanel {

    @Override
    public void paint(Graphics g) {
        super.paint(g);

        if (GameFrame.getInstance() != null && GameFrame.getInstance().getCapa_brillo().getBrightness() > 0f) {
            Graphics2D g2d = (Graphics2D) g.create();
            g2d.setColor(new Color(0, 0, 0, GameFrame.getInstance().getCapa_brillo().getBrightness()));
            g2d.fillRect(0, 0, getWidth(), getHeight());
            g2d.dispose();
        }
    }

    public JLabel getMessage() {
        return message;
    }

    public JLabel getSound_icon() {
        return sound_icon;
    }

    /**
     * Creates new form TTSNotifyPanel
     */
    public TTSNotifyPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        message = new javax.swing.JLabel();
        sound_icon = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));

        message.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        message.setForeground(new java.awt.Color(255, 255, 255));
        message.setText("TEXT");
        message.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        message.setDoubleBuffered(true);
        message.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(sound_icon)
                .addGap(0, 0, 0)
                .addComponent(message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sound_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel message;
    private javax.swing.JLabel sound_icon;
    // End of variables declaration//GEN-END:variables
}
