/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tonikelope.coronapoker;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author tonikelope
 */
public class VolumeControlDialog extends javax.swing.JDialog {

    public static final int TIMEOUT = 1;
    private volatile Timer timer = null;

    /**
     * Creates new form VolumeControl
     */
    public VolumeControlDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        setPreferredSize(new Dimension(Math.round(0.5f * parent.getWidth()), this.getHeight()));
        
        Helpers.updateFonts(this, Helpers.GUI_FONT, null);

        timer = new Timer(TIMEOUT * 1000, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {

                timer.stop();
                dispose();
                GameFrame.getInstance().volume_dialog = null;

            }
        });

        timer.setRepeats(false);
        timer.setCoalesce(false);
    }

    public void refresh() {

        Helpers.GUIRun(new Runnable() {
            public void run() {

                if (timer.isRunning()) {
                    timer.restart();
                } else {
                    timer.start();
                }

                barra.setValue(Math.round(Audio.MASTER_VOLUME * 100));

                sound_icon.setBackground(barra.getValue() > 0 ? Color.WHITE : Color.RED);

                if (!isVisible()) {
                    setVisible(true);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sound_icon = new javax.swing.JLabel();
        barra = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setFocusCycleRoot(false);
        setFocusable(false);
        setFocusableWindowState(false);
        setUndecorated(true);

        sound_icon.setBackground(new java.awt.Color(255, 255, 255));
        sound_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/volumen.png"))); // NOI18N
        sound_icon.setDoubleBuffered(true);
        sound_icon.setFocusable(false);
        sound_icon.setOpaque(true);

        barra.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        barra.setBorder(null);
        barra.setBorderPainted(false);
        barra.setDoubleBuffered(true);
        barra.setFocusable(false);
        barra.setStringPainted(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sound_icon)
                .addGap(0, 0, 0)
                .addComponent(barra, javax.swing.GroupLayout.PREFERRED_SIZE, 929, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sound_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(barra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barra;
    private javax.swing.JLabel sound_icon;
    // End of variables declaration//GEN-END:variables
}
