/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tonikelope.coronapoker;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author tonikelope
 */
public class VolumeControlDialog extends javax.swing.JDialog {

    public static final int TIMEOUT = 1000;
    private volatile Timer timer = null;

    /**
     * Creates new form VolumeControl
     */
    public VolumeControlDialog(java.awt.Dialog parent, boolean modal, int width) {
        super(parent, modal);
        initComponents();

        setPreferredSize(new Dimension(width, this.getHeight()));

        Helpers.updateFonts(this, Helpers.GUI_FONT, null);

        pack();

        timer = new Timer(TIMEOUT, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {

                timer.stop();
                dispose();
                Init.VOLUME_DIALOG = null;

            }
        });

        timer.setRepeats(false);
        timer.setCoalesce(false);
    }

    /**
     * Creates new form VolumeControl
     */
    public VolumeControlDialog(java.awt.Frame parent, boolean modal, int width) {
        super(parent, modal);
        initComponents();

        setPreferredSize(new Dimension(width, this.getHeight()));

        Helpers.updateFonts(this, Helpers.GUI_FONT, null);

        pack();

        timer = new Timer(TIMEOUT, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {

                timer.stop();
                dispose();
                Init.VOLUME_DIALOG = null;

            }
        });

        timer.setRepeats(false);
        timer.setCoalesce(false);
    }

    public void refresh() {

        Helpers.GUIRun(new Runnable() {
            public void run() {

                if (timer.isRunning()) {
                    timer.restart();
                } else {
                    timer.start();
                }

                barra.setValue(Math.round(Audio.MASTER_VOLUME * 100));

                sound_icon.setBackground(barra.getValue() > 0 ? Color.WHITE : Color.RED);
                panel.setBackground(barra.getValue() > 0 ? Color.WHITE : Color.RED);

                if (!isVisible()) {
                    setVisible(true);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        sound_icon = new javax.swing.JLabel();
        barra = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setFocusCycleRoot(false);
        setFocusable(false);
        setFocusableWindowState(false);
        setUndecorated(true);

        panel.setBackground(new java.awt.Color(255, 255, 255));

        sound_icon.setBackground(new java.awt.Color(255, 255, 255));
        sound_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/volumen.png"))); // NOI18N
        sound_icon.setDoubleBuffered(true);
        sound_icon.setFocusable(false);
        sound_icon.setOpaque(true);

        barra.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        barra.setBorder(null);
        barra.setBorderPainted(false);
        barra.setDoubleBuffered(true);
        barra.setFocusable(false);
        barra.setStringPainted(true);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sound_icon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sound_icon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(barra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barra;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel sound_icon;
    // End of variables declaration//GEN-END:variables
}
